apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redhat-ods-applications

resources:
  - gaudi-pytorch-base-image-stream.yaml
  - gaudi-pytorch-image-stream.yaml
  - gaudi-pytorch-base-build-config.yaml
  - gaudi-pytorch-build-config.yaml

generatorOptions:
  disableNameSuffixHash: true
