apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redhat-ods-applications

resources:
  - gaudi-datascience-base-image-stream.yaml
  - gaudi-datascience-image-stream.yaml
  - gaudi-datascience-base-build-config.yaml
  - gaudi-datascience-build-config.yaml

generatorOptions:
  disableNameSuffixHash: true
