apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - AnythingLLM-Custom-Workbench-Image.yaml
  - ODH-TEC-Custom-Workbench-Image.yaml
  - Gaudi-DataScience-Workbench-Image.yaml